example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from orders.views import HomeView, OrderView

app_name = 'getpaid_example'

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^order/(?P<pk>\d+)/$', OrderView.as_view(), name='order_detail'),
    url(r'', include('getpaid.urls', namespace='getpaid')),
]

getpaid/urls.py
from django.conf.urls import url, include
from getpaid.views import NewPaymentView, FallbackView
from getpaid.utils import import_backend_modules


app_name = 'getpaid'
namespace = app_name

includes_list = []
for backend_name, urls in import_backend_modules('urls').items():
    backend_url_regex = r'^%s/' % backend_name
    backend_namespace = backend_name.split('.')[-1]
    backend_url = url(
        backend_url_regex,
        include((urls, app_name), namespace=backend_namespace)
    )
    includes_list.append(backend_url)


urlpatterns = [
    url(
        r'^new/payment/(?P<currency>[A-Z]{3})/$',
        NewPaymentView.as_view(),
        name='new-payment'
    ),
    url(
        r'^payment/success/(?P<pk>\d+)/$',
        FallbackView.as_view(success=True),
        name='success-fallback'
    ),
    url(
        r'^payment/failure/(?P<pk>\d+)$',
        FallbackView.as_view(success=False),
        name='failure-fallback'
    ),
] + includes_list

example/orders/models.py
from django.db import models
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible

import getpaid

ORDER_STATUS_CHOICES = (
    ('W', 'Waiting for payment'),
    ('P', 'Payment complete')
)


@python_2_unicode_compatible
class Order(models.Model):
    """
    This is an example Order object. This one is very simple - is only one item,
    but you can easily create more complicated models with multi-items it does not matter
    for payment processing.
    """
    name = models.CharField(max_length=100, default="Lock, Stock and Two Smoking Barrels")
    total = models.DecimalField(decimal_places=2, max_digits=8, default='199.99')
    currency = models.CharField(max_length=3, default='EUR')
    status = models.CharField(max_length=1, blank=True, default='W',
                              choices=ORDER_STATUS_CHOICES)

    def get_absolute_url(self):
        return reverse('order_detail', kwargs={'pk': self.pk})

    def __str__(self):
        return self.name

    def clean(self):
        self.currency = self.currency.upper()


Payment = getpaid.register_to_payment(Order,
                                      unique=False,
                                      related_name='payments')

example/orders/forms.py
from decimal import Decimal
from django.core.exceptions import ValidationError
from django.forms.models import ModelForm
from .models import Order


class OrderForm(ModelForm):
    class Meta:
        model = Order
        exclude = ('status', )

    def clean_total(self):
        if self.cleaned_data['total'] <= Decimal('0'):
            raise ValidationError('Provide some reasonable item price')
        return self.cleaned_data['total']

example/orders/views.py
# Create your views here.
from django import http
from django.views import View
from django.views.generic import CreateView
from django.views.generic.detail import DetailView
from getpaid.forms import PaymentMethodForm
from .forms import OrderForm
from .models import Order


class HomeView(CreateView):
    model = Order
    template_name = 'home.html'
    form_class = OrderForm

    def get_context_data(self, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        context['orders'] = Order.objects.all()
        return context


class OrderView(DetailView):
    model = Order

    def get_context_data(self, **kwargs):
        context = super(OrderView, self).get_context_data(**kwargs)
        context['payment_form'] = PaymentMethodForm(
            self.object.currency,
            initial={'order': self.object}
        )
        return context


class PostGetter(View):
    def post(self, request, *args, **kwargs):
        return http.HttpResponse("OK")

example/orders/templates/orders/order_detail.html
<html>
<body>
<h1>Order #{{ object.pk }}</h1>
<p>
<a href="{% url 'home' %}">Home</a>
<p>
Order title: {{ object.name }}<br>
Order total: {{ object.total }} {{ object.currency }}
<p>

{% if order.status == 'W' %}
<h2>Choose payment type:</h2>
<form action="{% url 'getpaid:new-payment' currency=object.currency %}" method="post">
    {% csrf_token %}
    {{ payment_form.as_p }}
    <input type="submit" value="Continue">
</form>
{% endif %}

{% if order.status == 'P' %}
    This order was successfully paid.
{% endif %}


{% if order.payments.all %}
    <h2>Payments for order</h2>
    <p>(refresh this page to refresh payments status)
    <table border=1>
        <tr>
            <th>id</th>
            <th>amount</th>
            <th>status</th>
            <th>backend</th>
            <th>created on</th>
            <th>paid on</th>
            <th>amount_paid</th>
        </tr>
    {% for payment in order.payments.all %}
        <tr>
            <td>{{ payment.pk }}</td>
            <td>{{ payment.amount }} {{ payment.currency }}</td>
            <td>{{ payment.status }}</td>
            <td>{{ payment.backend }}</td>
            <td>{{ payment.created_on }}</td>
            <td>{{ payment.paid_on }}</td>
            <td>{{ payment.amount_paid }} {{ payment.currency }}</td>

        </tr>
    {% endfor %}
    </table>
{% endif %}
</body>
</html>